library(tidyverse)
library(ggpubr)
library(ggsci)

# assuming working directory is "script"

################# Check power analysis results (DIC) with ABC rejection ####################
get_res_all <- function(dir, files, nstat = 4){
  res_all = data.frame()
  for(i in 1:length(files)){
    #i = 1
    fields = strsplit(files[i], "_")[[1]]
    # ncell = str_replace(fields[2], "ncell", "")
    # fitness = str_replace(fields[3], "fitness", "")
    #
    fname = file.path(dir, files[i])
    res = read_table2(fname, col_names = F)

    # if(fitness == "0"){
    #   names(res) = c("chr_rate", "arm_rate", "birth_rate", "seed", "s1", "s2", "s3", "run", "dic_neutral", "dic_withsel")
    #   res$fitness = 0
    # }else{
    #   names(res) = c("chr_rate", "arm_rate", "birth_rate", "fitness", "seed", "s1", "s2", "s3", "run", "dic_neutral", "dic_withsel")
    # }

    if(nstat > 4){
      names(res) = c("ncell", "chr_rate", "arm_rate", "birth_rate", "fitness", "seed", "s1", "s2", "s3", "s4", "s5", "run", "dic_neutral", "dic_withsel")
    }else{
      names(res) = c("ncell", "chr_rate", "arm_rate", "birth_rate", "fitness", "seed", "s1", "s2", "s3", "s4", "run", "dic_neutral", "dic_withsel")
    }

    # res$sname = res$seed
    # seeds <- unique(res$seed)
    # new <- paste0("seed", seq(1:length(seeds)))
    # res$sname[res$sname %in% seeds] <- new[match(res$sname, seeds, nomatch = 0)]
    #unique(res$sname)

    #res$ncell = ncell
    res_all = rbind(res_all, res)
  }

  return(res_all)
}


plot_dic_release <- function(files, ndic, nsample, nstat = 4){
  res_all_orig = get_res_all(dir, files, nstat)
  #unique(res_all$ncell)
  res_all_orig %>% filter(ncell <= 60) -> res_all
  cell_levels = unique(res_all$ncell)
  fit_levels = unique(res_all$fitness)
  #res_all %>% select(ncell, fitness, seed, sname, run, dic_neutral, dic_withsel) -> res_sel
  res_all %>% select(ncell, fitness, seed, run, dic_neutral, dic_withsel) -> res_sel
  unique(res_sel$ncell)
  ntest = nrow(res_all_orig) / (length(cell_levels) * length(fit_levels))

  res_sel$ratio = res_sel$dic_neutral / res_sel$dic_withsel
  res_sel$delta = res_sel$dic_neutral - res_sel$dic_withsel
  res_sel$ncell = factor(res_sel$ncell, levels = c(seq(20, 100, 20), 200))
  res_sel$fitness = factor(res_sel$fitness, levels = c(0, seq(-0.2, -0.8, -0.2)))

  # both DICs are computed with the data generated by the same seed
  #res_sel %>% mutate(model=ifelse(ratio<1, "neutral evolution", "with selection")) %>% mutate(model=ifelse(ratio==1, "equal support", model)) -> res_all
  res_sel %>% mutate(model=ifelse(delta<0, "neutral", "selection")) %>% mutate(model=ifelse(delta==0, "equal support", model)) -> res_sel_annot
  res_sel_annot %>% group_by(ncell, fitness) %>% count(model) -> res_count
  res_count$model = factor(res_count$model, levels=c("selection", "neutral"))
  #res_count$ncell = factor(res_count$ncell, levels = seq(20, 100, 20))
  res_count$ncell = factor(res_count$ncell, levels = c(seq(20, 100, 20), 200))
  res_count$fitness = factor(res_count$fitness, levels = c(0, seq(-0.2, -0.8, -0.2)))
  #res_count$fitness = factor(res_count$fitness, levels = c(0, seq(-0.15, -0.45, -0.1)))
  pbar = ggplot(res_count, aes(x=(fitness), y=n, fill=model)) + geom_bar(stat="identity", width = 0.5) + theme_pubr() + xlab("") + ylab("") + facet_grid( . ~ ncell) + scale_fill_npg() + geom_hline(yintercept = ntest / 2, linetype = "dashed", color = "darkgrey") + theme(legend.position = "right")
  pbar
  # fout = file.path(dir, paste0("bar_ntest", ntest, "_ndic", ndic, "_nsample", nsample, "_mean", suffix, ".png"))
  # ggsave(fout, width = 9, height = 5)

  pal = pal_npg("nrc", alpha=1)(5)[3:5]
  #res_sel %>% filter(delta < 12) %>% filter(delta > -12) -> res_sel_norm
  pdelta = ggplot(res_sel, aes(x=fitness, y=log(ratio), fill=ncell)) +
    geom_boxplot(position = position_dodge()) +
    ylab("log(DIC_neutral/DIC_selection)") +
    #ylab("log(DIC1) - log(DIC2)") +
    theme_pubr()  + xlab("selection coefficient") + geom_hline(yintercept = 0, linetype="dashed", color = "darkgrey") + labs(fill = "#cells") + scale_y_continuous(n.breaks = 6) + theme(legend.position = "right") + scale_fill_manual(values = pal)
  pdelta
  #+ guides(fill = guide_legend(nrow = 1))
  # fout = file.path(dir, paste0("delta_by_cell_ntest", ntest, "_ndic", ndic, "_nsample", nsample, "_mean", suffix, ".png"))
  # ggsave(fout, width = 9, height = 5)
  #
  ggarrange(pbar, pdelta, nrow = 2)

  fout = file.path(dir, paste0("summary", ntest, "_ndic", ndic, "_nsample", nsample, "_mean", suffix, ".pdf"))
  ggsave(fout, width = 8, height = 5)
  fout = file.path(dir, paste0("summary", ntest, "_ndic", ndic, "_nsample", nsample, "_mean", suffix, ".png"))
  ggsave(fout, width = 8, height = 5)
}


dir = "../data/power_analysis/"
#dir = file.path(dir, "fixbrate")
ntest = 100

suffix = "_logs3_weight2.0"

#dir = file.path(dir, paste0("ntest", ntest))

ndic = 1
nsample = 100
files = list.files(dir, pattern = paste0("dic_.*ntest", ntest, "_ndic", ndic, "_nsample", nsample, ".*mean.*", suffix, ".tsv$"))
files

plot_dic_release(files, ndic, nsample)
